import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import BreakpointIndicator from "@/components/global/BreakpointIndicator";
import { Toaster } from "@/components/ui/sonner"
import { ProductModalProvider } from "@/contexts/productRegister-context";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/img/logoW.png",
  },
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <ProductModalProvider>
          <main className="flex-1">{children}</main>
          <BreakpointIndicator />
          <Toaster position="top-right" />
        </ProductModalProvider>
      </body>
    </html>
  );
}
