import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/global/sidebar";
import Navbar from "@/components/global/navbar";
import { ProductModalProvider } from "@/contexts/productRegister-context";
import ProductRegisterModal from "@/components/product/components/ProductRegisterModal";

export const metadata: Metadata = {
  title: "Store",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProductModalProvider>
      <SidebarProvider defaultOpen={false}>
        <AppSidebar />
        <main className="w-full h-screen flex flex-col">
          <ProductRegisterModal />
          <div className="flex-[5%]">
            <Navbar />
          </div>
          <div className="flex-[95%]">
            {children}
          </div>
        </main>
      </SidebarProvider>
    </ProductModalProvider>
  );
}
